/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateRouteImport } from './routes/create'
import { Route as WorkspaceSlugRouteImport } from './routes/$workspaceSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/$workspaceSlug/index'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'
import { Route as WorkspaceSlugSettingsRouteImport } from './routes/$workspaceSlug/settings'
import { Route as WorkspaceSlugReviewsRouteImport } from './routes/$workspaceSlug/reviews'
import { Route as WorkspaceSlugProfileRouteImport } from './routes/$workspaceSlug/profile'
import { Route as WorkspaceSlugMenuHistoryRouteImport } from './routes/$workspaceSlug/menu-history'
import { Route as WorkspaceSlugGatheringsNewRouteImport } from './routes/$workspaceSlug/gatherings.new'
import { Route as WorkspaceSlugGatheringsPostIdRouteImport } from './routes/$workspaceSlug/gatherings.$postId'
import { Route as WorkspaceSlugGatheringsPostIdIndexRouteImport } from './routes/$workspaceSlug/gatherings.$postId.index'
import { Route as WorkspaceSlugGatheringsPostIdEditRouteImport } from './routes/$workspaceSlug/gatherings.$postId.edit'

const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugSettingsRoute = WorkspaceSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugReviewsRoute = WorkspaceSlugReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugProfileRoute = WorkspaceSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const WorkspaceSlugMenuHistoryRoute =
  WorkspaceSlugMenuHistoryRouteImport.update({
    id: '/menu-history',
    path: '/menu-history',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugGatheringsNewRoute =
  WorkspaceSlugGatheringsNewRouteImport.update({
    id: '/gatherings/new',
    path: '/gatherings/new',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugGatheringsPostIdRoute =
  WorkspaceSlugGatheringsPostIdRouteImport.update({
    id: '/gatherings/$postId',
    path: '/gatherings/$postId',
    getParentRoute: () => WorkspaceSlugRoute,
  } as any)
const WorkspaceSlugGatheringsPostIdIndexRoute =
  WorkspaceSlugGatheringsPostIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkspaceSlugGatheringsPostIdRoute,
  } as any)
const WorkspaceSlugGatheringsPostIdEditRoute =
  WorkspaceSlugGatheringsPostIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => WorkspaceSlugGatheringsPostIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspaceSlug': typeof WorkspaceSlugRouteWithChildren
  '/create': typeof CreateRoute
  '/$workspaceSlug/menu-history': typeof WorkspaceSlugMenuHistoryRoute
  '/$workspaceSlug/profile': typeof WorkspaceSlugProfileRoute
  '/$workspaceSlug/reviews': typeof WorkspaceSlugReviewsRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/$workspaceSlug/': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/gatherings/$postId': typeof WorkspaceSlugGatheringsPostIdRouteWithChildren
  '/$workspaceSlug/gatherings/new': typeof WorkspaceSlugGatheringsNewRoute
  '/$workspaceSlug/gatherings/$postId/edit': typeof WorkspaceSlugGatheringsPostIdEditRoute
  '/$workspaceSlug/gatherings/$postId/': typeof WorkspaceSlugGatheringsPostIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/$workspaceSlug/menu-history': typeof WorkspaceSlugMenuHistoryRoute
  '/$workspaceSlug/profile': typeof WorkspaceSlugProfileRoute
  '/$workspaceSlug/reviews': typeof WorkspaceSlugReviewsRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/$workspaceSlug': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/gatherings/new': typeof WorkspaceSlugGatheringsNewRoute
  '/$workspaceSlug/gatherings/$postId/edit': typeof WorkspaceSlugGatheringsPostIdEditRoute
  '/$workspaceSlug/gatherings/$postId': typeof WorkspaceSlugGatheringsPostIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspaceSlug': typeof WorkspaceSlugRouteWithChildren
  '/create': typeof CreateRoute
  '/$workspaceSlug/menu-history': typeof WorkspaceSlugMenuHistoryRoute
  '/$workspaceSlug/profile': typeof WorkspaceSlugProfileRoute
  '/$workspaceSlug/reviews': typeof WorkspaceSlugReviewsRoute
  '/$workspaceSlug/settings': typeof WorkspaceSlugSettingsRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/$workspaceSlug/': typeof WorkspaceSlugIndexRoute
  '/$workspaceSlug/gatherings/$postId': typeof WorkspaceSlugGatheringsPostIdRouteWithChildren
  '/$workspaceSlug/gatherings/new': typeof WorkspaceSlugGatheringsNewRoute
  '/$workspaceSlug/gatherings/$postId/edit': typeof WorkspaceSlugGatheringsPostIdEditRoute
  '/$workspaceSlug/gatherings/$postId/': typeof WorkspaceSlugGatheringsPostIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceSlug'
    | '/create'
    | '/$workspaceSlug/menu-history'
    | '/$workspaceSlug/profile'
    | '/$workspaceSlug/reviews'
    | '/$workspaceSlug/settings'
    | '/join/$inviteCode'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/gatherings/$postId'
    | '/$workspaceSlug/gatherings/new'
    | '/$workspaceSlug/gatherings/$postId/edit'
    | '/$workspaceSlug/gatherings/$postId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/$workspaceSlug/menu-history'
    | '/$workspaceSlug/profile'
    | '/$workspaceSlug/reviews'
    | '/$workspaceSlug/settings'
    | '/join/$inviteCode'
    | '/$workspaceSlug'
    | '/$workspaceSlug/gatherings/new'
    | '/$workspaceSlug/gatherings/$postId/edit'
    | '/$workspaceSlug/gatherings/$postId'
  id:
    | '__root__'
    | '/'
    | '/$workspaceSlug'
    | '/create'
    | '/$workspaceSlug/menu-history'
    | '/$workspaceSlug/profile'
    | '/$workspaceSlug/reviews'
    | '/$workspaceSlug/settings'
    | '/join/$inviteCode'
    | '/$workspaceSlug/'
    | '/$workspaceSlug/gatherings/$postId'
    | '/$workspaceSlug/gatherings/new'
    | '/$workspaceSlug/gatherings/$postId/edit'
    | '/$workspaceSlug/gatherings/$postId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceSlugRoute: typeof WorkspaceSlugRouteWithChildren
  CreateRoute: typeof CreateRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug': {
      id: '/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/': {
      id: '/$workspaceSlug/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/settings': {
      id: '/$workspaceSlug/settings'
      path: '/settings'
      fullPath: '/$workspaceSlug/settings'
      preLoaderRoute: typeof WorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/reviews': {
      id: '/$workspaceSlug/reviews'
      path: '/reviews'
      fullPath: '/$workspaceSlug/reviews'
      preLoaderRoute: typeof WorkspaceSlugReviewsRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/profile': {
      id: '/$workspaceSlug/profile'
      path: '/profile'
      fullPath: '/$workspaceSlug/profile'
      preLoaderRoute: typeof WorkspaceSlugProfileRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/menu-history': {
      id: '/$workspaceSlug/menu-history'
      path: '/menu-history'
      fullPath: '/$workspaceSlug/menu-history'
      preLoaderRoute: typeof WorkspaceSlugMenuHistoryRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/gatherings/new': {
      id: '/$workspaceSlug/gatherings/new'
      path: '/gatherings/new'
      fullPath: '/$workspaceSlug/gatherings/new'
      preLoaderRoute: typeof WorkspaceSlugGatheringsNewRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/gatherings/$postId': {
      id: '/$workspaceSlug/gatherings/$postId'
      path: '/gatherings/$postId'
      fullPath: '/$workspaceSlug/gatherings/$postId'
      preLoaderRoute: typeof WorkspaceSlugGatheringsPostIdRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/$workspaceSlug/gatherings/$postId/': {
      id: '/$workspaceSlug/gatherings/$postId/'
      path: '/'
      fullPath: '/$workspaceSlug/gatherings/$postId/'
      preLoaderRoute: typeof WorkspaceSlugGatheringsPostIdIndexRouteImport
      parentRoute: typeof WorkspaceSlugGatheringsPostIdRoute
    }
    '/$workspaceSlug/gatherings/$postId/edit': {
      id: '/$workspaceSlug/gatherings/$postId/edit'
      path: '/edit'
      fullPath: '/$workspaceSlug/gatherings/$postId/edit'
      preLoaderRoute: typeof WorkspaceSlugGatheringsPostIdEditRouteImport
      parentRoute: typeof WorkspaceSlugGatheringsPostIdRoute
    }
  }
}

interface WorkspaceSlugGatheringsPostIdRouteChildren {
  WorkspaceSlugGatheringsPostIdEditRoute: typeof WorkspaceSlugGatheringsPostIdEditRoute
  WorkspaceSlugGatheringsPostIdIndexRoute: typeof WorkspaceSlugGatheringsPostIdIndexRoute
}

const WorkspaceSlugGatheringsPostIdRouteChildren: WorkspaceSlugGatheringsPostIdRouteChildren =
  {
    WorkspaceSlugGatheringsPostIdEditRoute:
      WorkspaceSlugGatheringsPostIdEditRoute,
    WorkspaceSlugGatheringsPostIdIndexRoute:
      WorkspaceSlugGatheringsPostIdIndexRoute,
  }

const WorkspaceSlugGatheringsPostIdRouteWithChildren =
  WorkspaceSlugGatheringsPostIdRoute._addFileChildren(
    WorkspaceSlugGatheringsPostIdRouteChildren,
  )

interface WorkspaceSlugRouteChildren {
  WorkspaceSlugMenuHistoryRoute: typeof WorkspaceSlugMenuHistoryRoute
  WorkspaceSlugProfileRoute: typeof WorkspaceSlugProfileRoute
  WorkspaceSlugReviewsRoute: typeof WorkspaceSlugReviewsRoute
  WorkspaceSlugSettingsRoute: typeof WorkspaceSlugSettingsRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
  WorkspaceSlugGatheringsPostIdRoute: typeof WorkspaceSlugGatheringsPostIdRouteWithChildren
  WorkspaceSlugGatheringsNewRoute: typeof WorkspaceSlugGatheringsNewRoute
}

const WorkspaceSlugRouteChildren: WorkspaceSlugRouteChildren = {
  WorkspaceSlugMenuHistoryRoute: WorkspaceSlugMenuHistoryRoute,
  WorkspaceSlugProfileRoute: WorkspaceSlugProfileRoute,
  WorkspaceSlugReviewsRoute: WorkspaceSlugReviewsRoute,
  WorkspaceSlugSettingsRoute: WorkspaceSlugSettingsRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
  WorkspaceSlugGatheringsPostIdRoute:
    WorkspaceSlugGatheringsPostIdRouteWithChildren,
  WorkspaceSlugGatheringsNewRoute: WorkspaceSlugGatheringsNewRoute,
}

const WorkspaceSlugRouteWithChildren = WorkspaceSlugRoute._addFileChildren(
  WorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceSlugRoute: WorkspaceSlugRouteWithChildren,
  CreateRoute: CreateRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
